### ISSUE TITLE
Navigatie pijlen op computer om door films te bladeren

### ISSUE THREAD

**Issue by wesleydebruijn** [wesleydebruijn/PathePlanner#7]

**Comment by jvhoven** [comment]
https://github.com/OwlFonk/OwlCarousel/issues/65

**Comment by wesleydebruijn** [comment]
Navigatie kan nu met scrollen

**Comment by jvhoven** [comment]
Goed bezig.

Op wo 9 dec. 2015 19:12 schreef Wesley de Bruijn notifications@github.com:
